apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-sy2-vgs-stc-tasktables
  namespace: processing

data:
  TaskTable_S3A_SY2_VGS_06_13.xml: |
    <?xml version="1.0" encoding="utf-8" standalone="no"?>
    <Ipf_Task_Table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <Processor_Name>S3A_SY2_VGS</Processor_Name>
        <Version>06.13</Version>
        <Test>No</Test>
        <Min_Disk_Space units="MB">2048</Min_Disk_Space>
        <Max_Time units="sec">1800</Max_Time>
        <List_of_Cfg_Files count="1">
            <Cfg_File>
                <File_Name>/usr/local/conf/S3IPF_SY2_VGS_06.13/S3A/S3IPF_SY2_VGS_Configuration.xml</File_Name>
            </Cfg_File>
        </List_of_Cfg_Files>
        <List_of_Dyn_ProcParams count="4">
            <Dyn_ProcParam>
                <Param_Name>facilityName</Param_Name>        <!-- Generation Centre -->
                <Param_Type>String</Param_Type>
                <Param_Default>MAR</Param_Default>
            </Dyn_ProcParam>
            <Dyn_ProcParam>
                <Param_Name>orderType</Param_Name> <!-- Timeliness of the product -->
                <Param_Type>String</Param_Type>
                <Param_Default>NRT</Param_Default>
            </Dyn_ProcParam>
            <Dyn_ProcParam>
                <Param_Name>hardwareName</Param_Name>          <!-- Platform (OPE,DEV...)-->
                <Param_Type>String</Param_Type>
                <Param_Default>D</Param_Default>
            </Dyn_ProcParam>
            <Dyn_ProcParam>
                <Param_Name>baselineCollection</Param_Name>          <!-- 001, ...-->
                <Param_Type>String</Param_Type>
                <Param_Default>002</Param_Default>
            </Dyn_ProcParam>
        </List_of_Dyn_ProcParams>  
        <Sensing_Time_flag>true</Sensing_Time_flag>
        <List_of_Pools count="1">
            <Pool>
                <Detached>false</Detached>
                <Killing_Signal>2</Killing_Signal>
                <List_of_Tasks count="1">
                    <!-- ================================ -->
                    <!-- L2 Processing of SYN VGS -->
                    <!-- ================================ -->
                    <Task>
                        <Name>SY2_VGS</Name>
                        <Version>06.13</Version>
                        <Critical>true</Critical>
                        <Criticality_Level>1</Criticality_Level>
                        <File_Name>/usr/local/components/S3IPF_SY2_VGS_06.13/bin/SY2_VGS.bin</File_Name>
                        <List_of_Inputs count="4">
                            <Input>
                                <Mode>ALWAYS</Mode>
                                <Mandatory>Yes</Mandatory>
                                <List_of_Alternatives count="2">
                                    <!-- SYN Level 2 trace VGK product -->
                                    <Alternative>
                                        <Order>1</Order>
                                        <Origin>DB</Origin>
                                        <Retrieval_Mode>ValIntersect</Retrieval_Mode>
                                        <T0>0</T0>
                                        <T1>0</T1>
                                        <File_Type>SY_2_VGK___</File_Type>
                                        <File_Name_Type>Physical</File_Name_Type>
                                    </Alternative>
                                    <!-- SYN Level 2 daily VG1 product -->
                                    <Alternative>
                                        <Order>2</Order>
                                        <Origin>DB</Origin>
                                        <Retrieval_Mode>ValIntersect</Retrieval_Mode>
                                        <T0>0</T0>
                                        <T1>0</T1>
                                        <File_Type>SY_2_VG1___</File_Type>
                                        <File_Name_Type>Physical</File_Name_Type>
                                    </Alternative>
                                </List_of_Alternatives>
                            </Input>
                           
                            <Input>
                                <Mode>ALWAYS</Mode>
                                <Mandatory>Yes</Mandatory>
                                <List_of_Alternatives count="4">
                                    <!-- Time initialization: FRO > FPO > OSF > BB2 -->
                                    <Alternative>
                                        <Order>1</Order>
                                        <Origin>DB</Origin>
                                        <Retrieval_Mode>LatestValCover</Retrieval_Mode>
                                        <T0>0</T0>
                                        <T1>0</T1>
                                        <File_Type>AX___FRO_AX</File_Type>
                                        <File_Name_Type>Physical</File_Name_Type>
                                    </Alternative>
                                    <Alternative>
                                        <Order>2</Order>
                                        <Origin>DB</Origin>
                                        <Retrieval_Mode>LatestValCover</Retrieval_Mode>
                                        <T0>0</T0>
                                        <T1>0</T1>
                                        <File_Type>AX___FPO_AX</File_Type>
                                        <File_Name_Type>Physical</File_Name_Type>
                                    </Alternative>
                                    <Alternative>
                                        <Order>3</Order>
                                        <Origin>DB</Origin>
                                        <Retrieval_Mode>LatestValCover</Retrieval_Mode>
                                        <T0>0</T0>
                                        <T1>0</T1>
                                        <File_Type>AX___OSF_AX</File_Type>
                                        <File_Name_Type>Physical</File_Name_Type>
                                    </Alternative>
                                    <Alternative>
                                        <Order>4</Order>
                                        <Origin>DB</Origin>
                                        <Retrieval_Mode>LatestValCover</Retrieval_Mode>
                                        <T0>0</T0>
                                        <T1>0</T1>
                                        <File_Type>AX___BB2_AX</File_Type>
                                        <File_Name_Type>Physical</File_Name_Type>
                                    </Alternative>
                                </List_of_Alternatives>
                            </Input>
                            
                            <Input>
                                <Mode>ALWAYS</Mode>
                                <Mandatory>Yes</Mandatory>
                                <List_of_Alternatives count="1">
                                    <Alternative>
                                        <Order>1</Order>
                                        <Origin>DB</Origin>
                                        <Retrieval_Mode>LatestValCover</Retrieval_Mode>
                                        <T0>0</T0>
                                        <T1>0</T1>
                                        <File_Type>AX___OSF_AX</File_Type>
                                        <File_Name_Type>Physical</File_Name_Type>
                                    </Alternative>
                                </List_of_Alternatives>
                            </Input>
                            
                            <Input>
                                <Mode>ALWAYS</Mode>
                                <Mandatory>Yes</Mandatory>
                                <List_of_Alternatives count="1">
                                    <Alternative>
                                        <Order>1</Order>
                                        <Origin>DB</Origin>
                                        <Retrieval_Mode>LatestValCover</Retrieval_Mode>
                                        <T0>0</T0>
                                        <T1>0</T1>
                                        <File_Type>SY_2_PCPSAX</File_Type>
                                        <File_Name_Type>Physical</File_Name_Type>
                                    </Alternative>
                                </List_of_Alternatives>
                            </Input>
                             
                        </List_of_Inputs>
                        
                        <List_of_Outputs count="2">
                            <Output>
                                <Destination>DBPROC</Destination>
                                <Mandatory>No</Mandatory>
                                <Type>SY_2_VG1___</Type>
                                <File_Name_Type>Directory</File_Name_Type>
                            </Output>
                            
                            <Output>
                                <Destination>DBPROC</Destination>
                                <Mandatory>No</Mandatory>
                                <Type>SY_2_V10___</Type>
                                <File_Name_Type>Directory</File_Name_Type>
                            </Output>
                        </List_of_Outputs>
                        <List_of_Breakpoints count="0"/>
    
                    </Task>
                </List_of_Tasks>
            </Pool>
        </List_of_Pools>
    </Ipf_Task_Table>
  TaskTable_S3B_SY2_VGS_06_13.xml: |
    <?xml version="1.0" encoding="utf-8" standalone="no"?>
    <Ipf_Task_Table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <Processor_Name>S3B_SY2_VGS</Processor_Name>
        <Version>06.13</Version>
        <Test>No</Test>
        <Min_Disk_Space units="MB">2048</Min_Disk_Space>
        <Max_Time units="sec">1800</Max_Time>
        <List_of_Cfg_Files count="1">
            <Cfg_File>
                <File_Name>/usr/local/conf/S3IPF_SY2_VGS_06.13/S3B/S3IPF_SY2_VGS_Configuration.xml</File_Name>
            </Cfg_File>
        </List_of_Cfg_Files>
        <List_of_Dyn_ProcParams count="4">
            <Dyn_ProcParam>
                <Param_Name>facilityName</Param_Name>        <!-- Generation Centre -->
                <Param_Type>String</Param_Type>
                <Param_Default>MAR</Param_Default>
            </Dyn_ProcParam>
            <Dyn_ProcParam>
                <Param_Name>orderType</Param_Name> <!-- Timeliness of the product -->
                <Param_Type>String</Param_Type>
                <Param_Default>NRT</Param_Default>
            </Dyn_ProcParam>
            <Dyn_ProcParam>
                <Param_Name>hardwareName</Param_Name>          <!-- Platform (OPE,DEV...)-->
                <Param_Type>String</Param_Type>
                <Param_Default>D</Param_Default>
            </Dyn_ProcParam>
            <Dyn_ProcParam>
                <Param_Name>baselineCollection</Param_Name>          <!-- 001, ...-->
                <Param_Type>String</Param_Type>
                <Param_Default>002</Param_Default>
            </Dyn_ProcParam>
        </List_of_Dyn_ProcParams>  
        <Sensing_Time_flag>true</Sensing_Time_flag>
        <List_of_Pools count="1">
            <Pool>
                <Detached>false</Detached>
                <Killing_Signal>2</Killing_Signal>
                <List_of_Tasks count="1">
                    <!-- ================================ -->
                    <!-- L2 Processing of SYN VGS -->
                    <!-- ================================ -->
                    <Task>
                        <Name>SY2_VGS</Name>
                        <Version>06.13</Version>
                        <Critical>true</Critical>
                        <Criticality_Level>1</Criticality_Level>
                        <File_Name>/usr/local/components/S3IPF_SY2_VGS_06.13/bin/SY2_VGS.bin</File_Name>
                        <List_of_Inputs count="4">
                            <Input>
                                <Mode>ALWAYS</Mode>
                                <Mandatory>Yes</Mandatory>
                                <List_of_Alternatives count="2">
                                    <!-- SYN Level 2 trace VGK product -->
                                    <Alternative>
                                        <Order>1</Order>
                                        <Origin>DB</Origin>
                                        <Retrieval_Mode>ValIntersect</Retrieval_Mode>
                                        <T0>0</T0>
                                        <T1>0</T1>
                                        <File_Type>SY_2_VGK___</File_Type>
                                        <File_Name_Type>Physical</File_Name_Type>
                                    </Alternative>
                                    <!-- SYN Level 2 daily VG1 product -->
                                    <Alternative>
                                        <Order>2</Order>
                                        <Origin>DB</Origin>
                                        <Retrieval_Mode>ValIntersect</Retrieval_Mode>
                                        <T0>0</T0>
                                        <T1>0</T1>
                                        <File_Type>SY_2_VG1___</File_Type>
                                        <File_Name_Type>Physical</File_Name_Type>
                                    </Alternative>
                                </List_of_Alternatives>
                            </Input>
                           
                            <Input>
                                <Mode>ALWAYS</Mode>
                                <Mandatory>Yes</Mandatory>
                                <List_of_Alternatives count="4">
                                    <!-- Time initialization: FRO > FPO > OSF > BB2 -->
                                    <Alternative>
                                        <Order>1</Order>
                                        <Origin>DB</Origin>
                                        <Retrieval_Mode>LatestValCover</Retrieval_Mode>
                                        <T0>0</T0>
                                        <T1>0</T1>
                                        <File_Type>AX___FRO_AX</File_Type>
                                        <File_Name_Type>Physical</File_Name_Type>
                                    </Alternative>
                                    <Alternative>
                                        <Order>2</Order>
                                        <Origin>DB</Origin>
                                        <Retrieval_Mode>LatestValCover</Retrieval_Mode>
                                        <T0>0</T0>
                                        <T1>0</T1>
                                        <File_Type>AX___FPO_AX</File_Type>
                                        <File_Name_Type>Physical</File_Name_Type>
                                    </Alternative>
                                    <Alternative>
                                        <Order>3</Order>
                                        <Origin>DB</Origin>
                                        <Retrieval_Mode>LatestValCover</Retrieval_Mode>
                                        <T0>0</T0>
                                        <T1>0</T1>
                                        <File_Type>AX___OSF_AX</File_Type>
                                        <File_Name_Type>Physical</File_Name_Type>
                                    </Alternative>
                                    <Alternative>
                                        <Order>4</Order>
                                        <Origin>DB</Origin>
                                        <Retrieval_Mode>LatestValCover</Retrieval_Mode>
                                        <T0>0</T0>
                                        <T1>0</T1>
                                        <File_Type>AX___BB2_AX</File_Type>
                                        <File_Name_Type>Physical</File_Name_Type>
                                    </Alternative>
                                </List_of_Alternatives>
                            </Input>
                            
                            <Input>
                                <Mode>ALWAYS</Mode>
                                <Mandatory>Yes</Mandatory>
                                <List_of_Alternatives count="1">
                                    <Alternative>
                                        <Order>1</Order>
                                        <Origin>DB</Origin>
                                        <Retrieval_Mode>LatestValCover</Retrieval_Mode>
                                        <T0>0</T0>
                                        <T1>0</T1>
                                        <File_Type>AX___OSF_AX</File_Type>
                                        <File_Name_Type>Physical</File_Name_Type>
                                    </Alternative>
                                </List_of_Alternatives>
                            </Input>
                            
                            <Input>
                                <Mode>ALWAYS</Mode>
                                <Mandatory>Yes</Mandatory>
                                <List_of_Alternatives count="1">
                                    <Alternative>
                                        <Order>1</Order>
                                        <Origin>DB</Origin>
                                        <Retrieval_Mode>LatestValCover</Retrieval_Mode>
                                        <T0>0</T0>
                                        <T1>0</T1>
                                        <File_Type>SY_2_PCPSAX</File_Type>
                                        <File_Name_Type>Physical</File_Name_Type>
                                    </Alternative>
                                </List_of_Alternatives>
                            </Input>
                             
                        </List_of_Inputs>
                        
                        <List_of_Outputs count="2">
                            <Output>
                                <Destination>DBPROC</Destination>
                                <Mandatory>No</Mandatory>
                                <Type>SY_2_VG1___</Type>
                                <File_Name_Type>Directory</File_Name_Type>
                            </Output>
                            
                            <Output>
                                <Destination>DBPROC</Destination>
                                <Mandatory>No</Mandatory>
                                <Type>SY_2_V10___</Type>
                                <File_Name_Type>Directory</File_Name_Type>
                            </Output>
                        </List_of_Outputs>
                        <List_of_Breakpoints count="0"/>
    
                    </Task>
                </List_of_Tasks>
            </Pool>
        </List_of_Pools>
    </Ipf_Task_Table>
